const API='https://script.google.com/macros/s/AKfycbyUOaqnkX1VSrBJ3Ee7IcPMcbRsmrikeotDfqn7IXsyvsCfcXS6CRDeF3o86Wzu366ojg/exec';
const COLORS=['#dc2626','#ea580c','#d99a00','#16803a','#2563eb'],SOFT=['#fef2f2','#fff7ed','#fffbeb','#f0fdf4','#eff6ff'];
const $=s=>document.querySelector(s), uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random(), today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}, fmt=n=>Number(n||0).toLocaleString('ko-KR');
let password='', accessToken=String(window.CHEONGUN_ACCESS_TOKEN||''), tab='home', selected=1, journalHouse=0, showBonus=false, haccpType='오늘점검';
let db=JSON.parse(localStorage.getItem('cheongun-local')||'null')||{placementDate:today(),bonus:3,houses:[20000,20000,20000,20000,20000],entries:[],shipments:[],haccp:[],medicine:[],queue:[]};
const saveLocal=()=>localStorage.setItem('cheongun-local',JSON.stringify(db));
const age=()=>Math.max(1,Math.min(40,Math.floor((new Date(today())-new Date(db.placementDate))/86400000)+1));
const toast=m=>{const x=$('#toast');x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2500)};
async function api(body){
 return new Promise((resolve,reject)=>{
  const timer=setTimeout(()=>reject(new Error('서버 응답 시간이 초과되었습니다.')),15000);
  google.script.run
   .withSuccessHandler(result=>{clearTimeout(timer);resolve(result)})
   .withFailureHandler(error=>{clearTimeout(timer);reject(new Error(error&&error.message?error.message:String(error)))})
   .apiRequest(JSON.stringify({...body,password,accessToken}));
 });
}
function setSync(cls,text){const x=$('#syncState');x.className='sync '+cls;x.textContent='● '+text}
async function sync(){if(!accessToken||!navigator.onLine){setSync('off','오프라인 저장');return}try{setSync('','동기화 중');if(db.queue.length){const q=[...db.queue],r=await api({action:'push',operations:q});if(!r.ok)throw Error(r.error);db.queue=[]}const pulled=await api({action:'pull'});if(!pulled.ok)throw Error(pulled.error);mergeRemote(pulled.data||{});saveLocal();setSync('ok','시트 동기화 완료');render()}catch(e){saveLocal();setSync('off','전송 대기 '+db.queue.length+'건')}}
function mergeById(local,remote,map){const all=new Map(local.map(x=>[x.id,x]));remote.forEach(r=>{if(String(r.deleted)==='true'||r.deleted===true)all.delete(String(r.id));else all.set(String(r.id),map(r))});return [...all.values()]}
function mergeRemote(data){db.entries=mergeById(db.entries,data['폐사도태기록']||[],r=>({id:String(r.id),date:String(r['날짜']).slice(0,10),age:Number(r['일령']),house:Number(r['동']),death:Number(r['폐사']||0),cull:Number(r['도태']||0),note:String(r['특이사항']||''),createdAt:String(r['입력시간']||r.updatedAt)}));db.shipments=mergeById(db.shipments,data['부분출하기록']||[],r=>({id:String(r.id),date:String(r['날짜']).slice(0,10),age:Number(r['일령']),house:Number(r['동']),count:Number(r['출하수']||0),note:String(r['특이사항']||''),createdAt:String(r['입력시간']||r.updatedAt)}));const hs=[];[['HACCP일일점검','오늘점검'],['소독방역기록','소독·방역'],['약품입고','약품관리'],['교육기록','교육']].forEach(([sheet,type])=>(data[sheet]||[]).forEach(r=>{if(String(r.deleted)!=='true')hs.push({id:String(r.id),date:String(r['날짜']).slice(0,10),type,house:Number(r['대상동']||0),target:String(r['작업구분']||r['참석자']||''),product:String(r['사용약품']||r['약품명']||r['교육명']||''),amount:Number(r['입고량']||0),unit:String(r['단위']||''),temp:String(r['온도']||''),humidity:String(r['습도']||''),detail:String(r['내용및조치']||r['교육내용']||''),createdAt:String(r['입력시간']||r.updatedAt)})}));db.haccp=mergeById(db.haccp,hs,x=>x);const flock=(data['사육회차']||[]).filter(x=>x['상태']==='진행중').sort((a,b)=>String(b['입추일']).localeCompare(String(a['입추일'])))[0];if(flock){db.placementDate=String(flock['입추일']).slice(0,10);db.bonus=Number(flock['덤비율']||3)}db.houses=[0,0,0,0,0];const houses=(data['계사정보']||[]).filter(x=>String(x['회차ID']).slice(0,10)===db.placementDate);houses.forEach(x=>{const n=Number(x['동']);if(n>=1&&n<=5)db.houses[n-1]=Number(x['공식입추수']||0)})}
function queue(sheet,row){db.queue.push({sheet,row});saveLocal();sync()}
function login(e){
 e.preventDefault();
 const p=$('#password').value;
 const message=$('#loginError');
 message.textContent='확인 중...';
 google.script.run
  .withSuccessHandler(function(result){
   if(!result||result.ok!==true){password='';message.textContent=(result&&result.error)||'비밀번호를 확인해주세요.';return}
   password='';accessToken=String(result.accessToken||'');message.textContent='자동접속 주소를 만드는 중...';
   if(result.autoUrl){window.top.location.href=result.autoUrl;return}
   $('#login').style.display='none';$('#login').hidden=true;$('#app').hidden=false;$('#app').style.display='block';render();setTimeout(sync,100);
  })
  .withFailureHandler(function(error){password='';message.textContent='서버 오류: '+(error&&error.message?error.message:String(error))})
  .apiRequest(JSON.stringify({action:'login',password:p}));
}
$('#loginForm').addEventListener('submit',login);$('#nav').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;tab=b.dataset.tab;document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===b));render()});
function render(){ $('#ageLabel').textContent=`입추 ${db.placementDate} · ${age()}일령`;({home:homeView,journal:journalViewExact,graph:graphView,ship:shipView,settings:settingsView,haccp:haccpView}[tab]||homeView)() }
function page(title,sub,body){$('#view').innerHTML=`<div class="page"><div class="title"><div><h1>${title}</h1><p>${sub}</p></div></div>${body}</div>`}
function todayByHouse(h){return db.entries.filter(x=>x.date===today()&&x.house===h).reduce((a,x)=>({death:a.death+x.death,cull:a.cull+x.cull}),{death:0,cull:0})}
function cumulative(h,key){return db.entries.filter(x=>x.house===h).reduce((s,x)=>s+Number(x[key]||0),0)}
function homeView(){page('당일 기록',`${today()} · ${age()}일령`,`
 <div class="card"><div class="houses">${[1,2,3,4,5].map(h=>`<button style="--c:${COLORS[h-1]}" data-house="${h}" class="${selected===h?'active':''}">${h}동</button>`).join('')}</div><div class="number-grid"><label>폐사수<input id="death" class="count-input active" type="text" inputmode="none" readonly value="0"></label><label>도태수<input id="cull" class="count-input" type="text" inputmode="none" readonly value="0"></label></div><div id="countTargetLabel" style="text-align:center;font-weight:800;margin:10px 0;color:#176b3a">폐사수 입력 중</div><div id="appKeypad" style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px">${[1,2,3,4,5,6,7,8,9].map(n=>`<button type="button" data-digit="${n}" style="min-height:52px;font-size:22px;font-weight:800">${n}</button>`).join('')}<button type="button" data-clear style="min-height:52px;font-weight:800">초기화</button><button type="button" data-digit="0" style="min-height:52px;font-size:22px;font-weight:800">0</button><button type="button" data-back style="min-height:52px;font-size:22px;font-weight:800">←</button></div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:8px 0 14px"><button type="button" data-add="1">+1</button><button type="button" data-add="5">+5</button><button type="button" data-add="10">+10</button><button type="button" data-add="-1">-1</button></div><label class="field">특이사항<textarea id="note" placeholder="특이사항이 있으면 입력하세요"></textarea></label><button id="saveEntry" class="save" style="--house:${COLORS[selected-1]}">${selected}동 기록 저장</button></div>
 <div class="card"><h2>오늘 동별 합계</h2><div class="totals">${[1,2,3,4,5].map(h=>{const t=todayByHouse(h);return `<div class="total-row" style="--c:${COLORS[h-1]};--soft:${SOFT[h-1]}"><strong>${h}동</strong><div><span>합계</span><b>${t.death+t.cull}</b></div><div><span>폐사</span><b>${t.death}</b></div><div><span>도태</span><b>${t.cull}</b></div></div>`}).join('')}</div></div>
 <div class="card records"><h2>오늘 입력기록 · 동별 시간순</h2>${db.entries.filter(x=>x.date===today()).sort((a,b)=>a.house-b.house||String(a.createdAt).localeCompare(String(b.createdAt))).map(x=>`<div class="record" style="border-left:7px solid ${COLORS[x.house-1]};background:${SOFT[x.house-1]}"><strong style="color:${COLORS[x.house-1]}">${x.house}동</strong><div><b>폐사 ${x.death} · 도태 ${x.cull} · 합계 ${x.death+x.cull}</b><span>${x.note||'특이사항 없음'}</span><small>${new Date(x.createdAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</small></div><button data-del-entry="${x.id}">삭제</button></div>`).join('')||'<p class="empty">오늘 입력한 기록이 없습니다.</p>'}</div>`);
 let activeCount='death';const activateCount=id=>{activeCount=id;document.querySelectorAll('.count-input').forEach(x=>x.classList.toggle('active',x.id===id));$('#countTargetLabel').textContent=(id==='death'?'폐사수':'도태수')+' 입력 중'};document.querySelectorAll('.count-input').forEach(x=>x.onclick=()=>activateCount(x.id));document.querySelectorAll('[data-digit]').forEach(b=>b.onclick=()=>{const x=$('#'+activeCount),digit=b.dataset.digit;x.value=x.value==='0'?digit:String(Math.min(9999,Number(x.value+digit)))});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const x=$('#'+activeCount);x.value=Math.max(0,Math.min(9999,Number(x.value||0)+Number(b.dataset.add)))});$('[data-clear]').onclick=()=>{$('#'+activeCount).value=0};$('[data-back]').onclick=()=>{const x=$('#'+activeCount);x.value=x.value.length>1?x.value.slice(0,-1):0};
 document.querySelectorAll('[data-house]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.house);homeView()});$('#saveEntry').onclick=()=>{const death=Number($('#death').value),cull=Number($('#cull').value),note=$('#note').value.trim();if(!death&&!cull&&!note)return toast('입력할 내용을 확인하세요');const row={id:uid(),회차ID:db.placementDate,날짜:today(),일령:age(),동:selected,폐사:death,도태:cull,특이사항:note,입력시간:new Date().toISOString(),기기ID:deviceId(),updatedAt:new Date().toISOString(),deleted:false};db.entries.push({id:row.id,date:row.날짜,age:row.일령,house:selected,death,cull,note,createdAt:row.입력시간});queue('폐사도태기록',row);toast(`${selected}동 기록 저장 완료`);homeView()};document.querySelectorAll('[data-del-entry]').forEach(b=>b.onclick=()=>{if(!confirm('정말로 이 기록을 삭제하시겠습니까?'))return;const x=db.entries.find(y=>y.id===b.dataset.delEntry);if(!x)return;db.entries=db.entries.filter(y=>y.id!==x.id);queue('폐사도태기록',{id:x.id,회차ID:db.placementDate,날짜:x.date,일령:x.age,동:x.house,폐사:x.death,도태:x.cull,특이사항:x.note,입력시간:x.createdAt,기기ID:deviceId(),deleted:true});homeView()})}
function journalView(){
 const currentAge=age(), bonusRate=showBonus?Number(db.bonus||0):0;
 const baseCount=h=>Math.round(Number(db.houses[h-1]||0)*(1+bonusRate/100));
 const dayStat=(h,d)=>db.entries.filter(x=>x.house===h&&x.age===d).reduce((a,x)=>({death:a.death+Number(x.death||0),cull:a.cull+Number(x.cull||0),notes:[...a.notes,...(x.note?[x.note]:[])]}),{death:0,cull:0,notes:[]});
 const houseStat=(h,d=currentAge)=>{const es=db.entries.filter(x=>x.house===h&&x.age<=d),death=es.reduce((s,x)=>s+Number(x.death||0),0),cull=es.reduce((s,x)=>s+Number(x.cull||0),0),shipped=db.shipments.filter(x=>x.house===h&&x.age<=d).reduce((s,x)=>s+Number(x.count||0),0),initial=baseCount(h),current=initial-death-cull-shipped,growth=initial?((current+shipped)/initial*100):0;return{initial,death,cull,shipped,current,growth}};
 const houses=journalHouse?[journalHouse]:[1,2,3,4,5], totals=houses.map(h=>houseStat(h));
 const total={initial:totals.reduce((s,x)=>s+x.initial,0),death:totals.reduce((s,x)=>s+x.death,0),cull:totals.reduce((s,x)=>s+x.cull,0),shipped:totals.reduce((s,x)=>s+x.shipped,0),current:totals.reduce((s,x)=>s+x.current,0)};total.growth=total.initial?((total.current+total.shipped)/total.initial*100):0;
 const summaryCards=(journalHouse?[journalHouse]:[1,2,3,4,5]).map(h=>{const s=houseStat(h);return `<div style="border-left:8px solid ${COLORS[h-1]};background:${SOFT[h-1]};padding:13px;border-radius:13px;margin-top:8px"><div style="display:flex;justify-content:space-between;align-items:center"><strong style="font-size:20px;color:${COLORS[h-1]}">${h}동</strong><b style="font-size:20px">현재 ${fmt(s.current)}수</b></div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:5px;text-align:center;margin-top:10px"><span>폐사<br><b>${fmt(s.death)}</b></span><span>도태<br><b>${fmt(s.cull)}</b></span><span>폐·도태<br><b>${fmt(s.death+s.cull)}</b></span><span>육성률<br><b>${s.growth.toFixed(2)}%</b></span></div></div>`}).join('');
 let body='';
 if(journalHouse===0){
  const rows=[];for(let d=currentAge;d>=1;d--){const cells=[1,2,3,4,5].map(h=>{const x=dayStat(h,d),s=houseStat(h,d);return `<td style="min-width:150px;background:${SOFT[h-1]}"><b style="color:${COLORS[h-1]}">폐 ${x.death} · 도 ${x.cull}</b><br><span>합계 ${x.death+x.cull}</span><br><strong>현재 ${fmt(s.current)}</strong></td>`});const all=[1,2,3,4,5].reduce((a,h)=>{const x=dayStat(h,d);return{death:a.death+x.death,cull:a.cull+x.cull}},{death:0,cull:0});const allCurrent=[1,2,3,4,5].reduce((s,h)=>s+houseStat(h,d).current,0);rows.push(`<tr><th style="position:sticky;left:0;background:#fff;min-width:70px">${d}일령</th><td style="min-width:150px;background:#edf7f0"><b>폐 ${all.death} · 도 ${all.cull}</b><br><span>합계 ${all.death+all.cull}</span><br><strong>현재 ${fmt(allCurrent)}</strong></td>${cells.join('')}</tr>`)}
  body=`<div class="card"><div class="table-wrap"><table style="border-collapse:separate;border-spacing:4px;width:max-content;text-align:center"><thead><tr><th>일령</th><th>동합계</th>${[1,2,3,4,5].map(h=>`<th style="color:${COLORS[h-1]}">${h}동</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div></div>`;
 }else{
  const rows=[];for(let d=currentAge;d>=1;d--){const x=dayStat(journalHouse,d),s=houseStat(journalHouse,d);rows.push(`<div data-edit-age="${d}" style="display:grid;grid-template-columns:58px repeat(4,minmax(55px,1fr));gap:5px;align-items:center;padding:12px 6px;border-bottom:1px solid #ddd;background:${SOFT[journalHouse-1]}"><b style="color:${COLORS[journalHouse-1]}">${d}일령</b><span>폐사<br><b>${x.death}</b></span><span>도태<br><b>${x.cull}</b></span><span>합계<br><b>${x.death+x.cull}</b></span><span>현재<br><b>${fmt(s.current)}</b></span><small style="grid-column:2/6">${x.notes.join(' / ')||'특이사항 없음'} · <u>눌러서 수정</u></small></div>`)}body=`<div class="card"><h2>${journalHouse}동 일령별 기록</h2>${rows.join('')}</div>`;
 }
 page('일령별 사육일지',`${currentAge}일령 · 최근 일령부터 표시`,`<div class="card"><div style="display:flex;justify-content:space-between;align-items:center"><div><b>${journalHouse?journalHouse+'동':'1~5동 전체'} 현황</b><p style="margin:4px 0">현재 ${fmt(total.current)}수 · 폐·도태 ${fmt(total.death+total.cull)}수 · 육성률 ${total.growth.toFixed(2)}%</p></div><button id="bonusToggle" style="font-size:12px;padding:7px 9px">${showBonus?'공식 수치로':'덤 포함 참고'}</button></div><div class="houses" style="margin-top:10px">${[0,1,2,3,4,5].map(h=>`<button data-jhouse="${h}" style="--c:${h?COLORS[h-1]:'#176b3a'}" class="${journalHouse===h?'active':''}">${h?h+'동':'전체'}</button>`).join('')}</div>${summaryCards}</div>${body}`);
 document.querySelectorAll('[data-jhouse]').forEach(b=>b.onclick=()=>{journalHouse=Number(b.dataset.jhouse);journalView()});$('#bonusToggle').onclick=()=>{showBonus=!showBonus;journalView()};document.querySelectorAll('[data-edit-age]').forEach(r=>r.onclick=()=>editJournalDay(journalHouse,Number(r.dataset.editAge),dayStat(journalHouse,Number(r.dataset.editAge))))
}
function editJournalDay(h,d,current){const death=prompt(`${h}동 ${d}일령 폐사수`,String(current.death));if(death===null)return;const cull=prompt(`${h}동 ${d}일령 도태수`,String(current.cull));if(cull===null)return;const note=prompt(`${h}동 ${d}일령 특이사항`,current.notes.join(' / '));if(note===null)return;const dd=Number(death)-current.death,dc=Number(cull)-current.cull;if(!dd&&!dc&&note===current.notes.join(' / '))return toast('변경된 내용이 없습니다');const date=new Date(new Date(db.placementDate).getTime()+(d-1)*86400000),dateText=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`,row={id:uid(),회차ID:db.placementDate,날짜:dateText,일령:d,동:h,폐사:dd,도태:dc,특이사항:'[수정] '+note,입력시간:new Date().toISOString(),기기ID:deviceId(),updatedAt:new Date().toISOString(),deleted:false};db.entries.push({id:row.id,date:dateText,age:d,house:h,death:dd,cull:dc,note:row.특이사항,createdAt:row.입력시간});queue('폐사도태기록',row);toast(`${h}동 ${d}일령 수정 완료`);journalViewExact()}
function journalViewExact(){
 const ca=age(),rate=showBonus?Number(db.bonus||0):0;
 const officialInitial=h=>Number(db.houses[h-1]||0);
 const bonusCount=h=>Math.round(officialInitial(h)*rate/100);
 const daily=(h,d)=>db.entries.filter(x=>x.house===h&&x.age===d).reduce((a,x)=>({death:a.death+Number(x.death||0),cull:a.cull+Number(x.cull||0),notes:a.notes.concat(x.note?[x.note]:[])}),{death:0,cull:0,notes:[]});
 const stat=(h,d=ca)=>{const es=db.entries.filter(x=>x.house===h&&x.age<=d),death=es.reduce((s,x)=>s+Number(x.death||0),0),cull=es.reduce((s,x)=>s+Number(x.cull||0),0),ship=db.shipments.filter(x=>x.house===h&&x.age<=d).reduce((s,x)=>s+Number(x.count||0),0),start=officialInitial(h),bonus=bonusCount(h),current=start+bonus-death-cull-ship,growth=start?((current+ship)/start*100):0;return{death,cull,ship,start,bonus,current,growth}};
 const stats=[1,2,3,4,5].map(h=>stat(h)),sum=k=>stats.reduce((s,x)=>s+x[k],0),totalStart=sum('start'),totalCurrent=sum('current'),totalShip=sum('ship'),totalLoss=sum('death')+sum('cull'),totalGrowth=totalStart?((totalCurrent+totalShip)/totalStart*100):0;
 const compactStyle=`<style>.jcompact{font-size:13px}.jcompact .jtabs{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:4px;margin-bottom:8px}.jcompact .jtabs button{min-width:0;padding:9px 1px;font-size:13px;border-width:1px}.jcompact table{font-size:11px;line-height:1.2;table-layout:fixed}.jcompact th,.jcompact td{padding:7px 2px!important;white-space:normal!important;word-break:keep-all}.jcompact h2{font-size:20px;margin:14px 0 8px}@media(max-width:380px){.jcompact{font-size:12px}.jcompact table{font-size:10px}.jcompact .jtabs button{font-size:12px;padding:8px 0}}</style>`;
 const tabs=`<div class="jtabs">${[0,1,2,3,4,5].map(h=>`<button data-jhouse="${h}" style="--c:${h?COLORS[h-1]:'#176b3a'};border-color:${h?COLORS[h-1]:'#176b3a'};color:${journalHouse===h?'#fff':(h?COLORS[h-1]:'#176b3a')};background:${journalHouse===h?(h?COLORS[h-1]:'#176b3a'):'#fff'}" class="${journalHouse===h?'active':''}">${h?h+'동':'전체'}</button>`).join('')}</div>`;
 const toggle=`<button id="bonusToggle" style="width:100%;padding:9px;border:1px solid #d5e4da;background:#fff;border-radius:10px;color:#176b3a;font-weight:800">${showBonus?'비공식 덤 포함 기준':'공식 입추수 기준'} <small style="float:right;color:#657169">${showBonus?'✓ 동별 덤 '+db.bonus+'%를 생존수에 포함':'동별 덤 '+db.bonus+'% 포함 참고'}</small></button>`;
 if(journalHouse===0){
  const cards=stats.map((s,i)=>`<div style="display:grid;grid-template-columns:48px repeat(4,1fr);align-items:center;border:1px solid ${COLORS[i]}55;background:${SOFT[i]};border-radius:9px;overflow:hidden;margin:5px 0;min-height:48px"><b style="height:100%;display:grid;place-items:center;background:${COLORS[i]};color:#fff;font-size:17px">${i+1}동</b><span style="text-align:center;font-size:11px"><small>현재</small><br><b style="font-size:14px;color:${COLORS[i]}">${fmt(s.current)}</b></span><span style="text-align:center;font-size:11px"><small>육성률</small><br><b style="font-size:14px;color:${COLORS[i]}">${s.growth.toFixed(2)}%</b></span><span style="text-align:center;font-size:11px"><small>부분<br>출하</small><br><b style="font-size:14px;color:${COLORS[i]}">${fmt(s.ship)}</b></span><span style="text-align:center;font-size:11px"><small>폐·도태</small><br><b style="font-size:14px;color:${COLORS[i]}">${fmt(s.death+s.cull)}</b></span></div>`).join('');
  const summary=`<div style="display:grid;grid-template-columns:repeat(4,1fr);border:2px solid #16803a;border-radius:10px;padding:8px 2px;text-align:center;margin:8px 0;font-size:10px"><span><small>전체 현재<br>사육수</small><br><b style="font-size:16px;color:#08783d">${fmt(totalCurrent)}</b></span><span><small>전체<br>육성률</small><br><b style="font-size:16px;color:#08783d">${totalGrowth.toFixed(2)}%</b></span><span><small>누적 부분<br>출하</small><br><b style="font-size:16px;color:#08783d">${fmt(totalShip)}</b></span><span><small>누적<br>폐·도태</small><br><b style="font-size:16px;color:#dc2626">${fmt(totalLoss)}</b></span></div>`;
  const fixed=[['현재 사육수',fmt(totalCurrent),...stats.map(x=>fmt(x.current))],['육성률',totalGrowth.toFixed(2)+'%',...stats.map(x=>x.growth.toFixed(2)+'%')],['누적 폐·도태 합계',fmt(totalLoss),...stats.map(x=>fmt(x.death+x.cull))],['누적 부분출하',fmt(totalShip),...stats.map(x=>fmt(x.ship))]];
  let rows=fixed.map(r=>`<tr>${r.map((v,j)=>`<${j?'td':'th'} style="padding:10px 7px;border:1px solid #dce5df;white-space:nowrap;${j===1?'background:#fff6d8;font-weight:800;':''}${j>1?'color:'+COLORS[j-2]+';':''}">${v}</${j?'td':'th'}>`).join('')}</tr>`).join('');
  for(let d=ca;d>=1;d--){const vals=[1,2,3,4,5].map(h=>{const x=daily(h,d);return x.death+x.cull});rows+=`<tr><th style="padding:10px 7px;border:1px solid #dce5df;white-space:nowrap">${d}일령${d===ca?' <small style="background:#16803a;color:#fff;border-radius:8px;padding:2px 5px">현재</small>':''}</th><td style="padding:10px;border:1px solid #dce5df;background:#fff6d8;font-weight:800">${vals.reduce((a,b)=>a+b,0)}</td>${vals.map((v,i)=>`<td style="padding:10px;border:1px solid #dce5df;color:${COLORS[i]}">${v}</td>`).join('')}</tr>`}
  const table=`<div class="card" style="padding:10px 4px"><h2>일령별 전체 기록</h2><p style="text-align:right;font-size:10px">최근 일령이 위로 옵니다.</p><div class="table-wrap"><table style="border-collapse:collapse;width:100%;min-width:0;text-align:center"><colgroup><col style="width:25%"><col style="width:12.5%"><col style="width:12.5%"><col style="width:12.5%"><col style="width:12.5%"><col style="width:12.5%"><col style="width:12.5%"></colgroup><thead><tr><th style="background:#edf4ef">구분</th><th style="background:#fff1ba">동<br>합계</th>${[1,2,3,4,5].map(h=>`<th style="color:${COLORS[h-1]};background:#edf4ef">${h}동</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div></div>`;
  page('일령별 사육일지','전년도는 보낸 기록을 확인합니다',`${compactStyle}<div class="jcompact">${tabs}${toggle}<h2>${ca}일령 전체 현황</h2>${cards}${summary}${table}</div>`);
 }else{
  const s=stat(journalHouse),card=`<div style="border:2px solid ${COLORS[journalHouse-1]};background:${SOFT[journalHouse-1]};border-radius:13px;padding:14px"><div style="display:flex;justify-content:space-between"><b style="font-size:22px;color:${COLORS[journalHouse-1]}">${journalHouse}동</b><strong style="font-size:22px">현재 ${fmt(s.current)}수</strong></div><div style="display:grid;grid-template-columns:repeat(4,1fr);text-align:center;margin-top:12px"><span>육성률<br><b>${s.growth.toFixed(2)}%</b></span><span>폐사<br><b>${s.death}</b></span><span>도태<br><b>${s.cull}</b></span><span>부분출하<br><b>${s.ship}</b></span></div></div>`;
  let rows='';for(let d=ca;d>=1;d--){const x=daily(journalHouse,d),ds=stat(journalHouse,d);rows+=`<tr data-edit-age="${d}" style="background:${SOFT[journalHouse-1]}"><th>${d}일령</th><td>${x.death}</td><td>${x.cull}</td><td><b>${x.death+x.cull}</b></td><td><b>${fmt(ds.current)}</b></td><td style="min-width:150px;text-align:left">${x.notes.join(' / ')||'-'}</td><td><button type="button">수정</button></td></tr>`}
  const table=`<div class="card"><h2>${journalHouse}동 일령별 기록</h2><div class="table-wrap"><table style="border-collapse:collapse;width:100%;min-width:650px;text-align:center"><thead><tr><th>일령</th><th>폐사</th><th>도태</th><th>합계</th><th>현재 사육수</th><th>특이사항</th><th>수정</th></tr></thead><tbody>${rows}</tbody></table></div></div>`;
  page('일령별 사육일지',`${journalHouse}동 상세기록`,`${compactStyle}<div class="jcompact">${tabs}${toggle}<h2>${ca}일령 ${journalHouse}동 현황</h2>${card}${table}</div>`);
 }
 document.querySelectorAll('[data-jhouse]').forEach(b=>b.onclick=()=>{journalHouse=Number(b.dataset.jhouse);journalViewExact()});$('#bonusToggle').onclick=()=>{showBonus=!showBonus;journalViewExact()};document.querySelectorAll('[data-edit-age]').forEach(r=>r.onclick=()=>editJournalDay(journalHouse,Number(r.dataset.editAge),daily(journalHouse,Number(r.dataset.editAge))))
}
function graphView(){const vals=[1,2,3,4,5].map(h=>cumulative(h,'death')+cumulative(h,'cull')),max=Math.max(1,...vals);page('그래프 보기','동별 누적 폐·도태',`<div class="card bars">${vals.map((v,i)=>`<div class="bar" style="--c:${COLORS[i]};--w:${Math.max(3,v/max*100)}%"><b>${i+1}동</b><i></i><strong>${v}수</strong></div>`).join('')}</div>`)}
function shipView(){page('부분출하','출하 즉시 현재 사육수에 반영',`<div class="card"><div class="houses">${[1,2,3,4,5].map(h=>`<button style="--c:${COLORS[h-1]}" data-house="${h}" class="${selected===h?'active':''}">${h}동</button>`).join('')}</div><div class="number-grid"><label>부분출하수<input id="shipCount" type="number" inputmode="numeric" min="0"></label><label>출하일<input id="shipDate" type="date" value="${today()}"></label></div><label class="field">특이사항<textarea id="shipNote"></textarea></label><button id="saveShip" class="save" style="--house:${COLORS[selected-1]}">${selected}동 부분출하 저장</button></div><div class="card records"><h2>부분출하 기록</h2>${db.shipments.slice().reverse().map(x=>`<div class="record"><strong>${x.house}동</strong><div><b>${fmt(x.count)}수</b><span>${x.date} · ${x.note||'특이사항 없음'}</span></div></div>`).join('')||'<p class="empty">기록이 없습니다.</p>'}</div>`);document.querySelectorAll('[data-house]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.house);shipView()});$('#saveShip').onclick=()=>{const count=Number($('#shipCount').value);if(!count)return;const row={id:uid(),회차ID:db.placementDate,날짜:$('#shipDate').value,일령:age(),동:selected,출하수:count,특이사항:$('#shipNote').value,입력시간:new Date().toISOString(),기기ID:deviceId(),deleted:false};db.shipments.push({id:row.id,date:row.날짜,age:row.일령,house:selected,count,note:row.특이사항});queue('부분출하기록',row);toast('부분출하 저장 완료');shipView()}}
function settingsView(){page('사육 회차 설정','한 파스 종료 시 새 회차 시작',`<div class="card"><label class="field">입추일<input id="placement" type="date" value="${db.placementDate}"></label><label class="field">덤 비율(참고)<input id="bonus" type="number" step=".1" value="${db.bonus}"></label>${db.houses.map((n,i)=>`<div class="setting-row"><b>${i+1}동 공식 입추수</b><input data-official="${i}" type="number" value="${n}"></div>`).join('')}<button id="saveSettings" class="save" style="--house:var(--g);margin-top:14px">설정 저장</button></div><div class="card"><b>시트 기준 전체 새로고침</b><p>시트에서 기록을 직접 수정·삭제한 경우 이 휴대전화의 저장자료를 지우고 시트 내용만 다시 받습니다.</p><button id="forceReload" class="save" style="--house:#4b5563">시트 기준으로 전체 새로고침</button></div><div class="card"><b>새 사육 회차</b><p>전량 출하 후 시작하면 사육기록만 새로 시작하며 HACCP 자료는 계속 보존됩니다.</p><button id="newFlock" class="save" style="--house:#8b2f2f">새 파스 시작</button></div>`);$('#saveSettings').onclick=()=>{db.placementDate=$('#placement').value;db.bonus=Number($('#bonus').value);document.querySelectorAll('[data-official]').forEach(x=>db.houses[Number(x.dataset.official)]=Number(x.value));queue('사육회차',{id:db.placementDate,입추일:db.placementDate,종료일:'',상태:'진행중',덤비율:db.bonus,createdAt:new Date().toISOString()});db.houses.forEach((n,i)=>queue('계사정보',{id:`${db.placementDate}-${i+1}`,회차ID:db.placementDate,동:i+1,공식입추수:n,createdAt:new Date().toISOString()}));saveLocal();toast('설정 저장 완료');render()};$('#forceReload').onclick=forceReloadFromSheet;$('#newFlock').onclick=()=>{if(!confirm('사육기록을 새 파스로 시작할까요? HACCP 기록은 유지됩니다.'))return;db.entries=[];db.shipments=[];db.placementDate=today();saveLocal();render()}}
async function forceReloadFromSheet(){const waiting=db.queue.length,warning=waiting?`아직 시트로 전송되지 않은 ${waiting}건의 기록도 삭제됩니다.\n\n`:'';if(!confirm(warning+'정말로 이 휴대전화의 자료를 지우고 시트 기준으로 다시 받으시겠습니까?'))return;try{setSync('','시트 자료 받는 중');const pulled=await api({action:'pull'});if(!pulled.ok)throw Error(pulled.error);db={placementDate:today(),bonus:3,houses:[0,0,0,0,0],entries:[],shipments:[],haccp:[],medicine:[],queue:[]};mergeRemote(pulled.data||{});saveLocal();setSync('ok','시트 기준 새로고침 완료');toast('시트 내용으로 새로고침했습니다');render()}catch(e){setSync('off','새로고침 실패');alert('시트 새로고침 실패: '+(e.message||e))}}
function haccpView(){const types=['오늘점검','소독·방역','약품관리','교육'],records=db.haccp.filter(x=>x.type===haccpType).sort((a,b)=>b.date.localeCompare(a.date));page('HACCP 상시관리','사육 파스와 별도로 계속 보관',`<div class="card report-tools"><select id="reportYear"><option>${new Date().getFullYear()}</option><option>${new Date().getFullYear()-1}</option></select><select id="reportQ">${[1,2,3,4].map(q=>`<option value="${q}" ${Math.floor(new Date().getMonth()/3)+1===q?'selected':''}>${q}분기</option>`).join('')}</select><button id="printQuarter">분기 PDF</button></div><div class="haccp-types">${types.map(x=>`<button data-type="${x}" class="${haccpType===x?'active':''}">${x}</button>`).join('')}</div><div class="card" style="margin-top:10px"><label class="field">기록일<input id="hDate" type="date" value="${today()}"></label><div class="houses" style="margin:10px 0">${[0,1,2,3,4,5].map(h=>`<button style="--c:${h?COLORS[h-1]:'#176b3a'}" data-hhouse="${h}" class="${selected===h?'active':''}">${h?`${h}동`:'전체'}</button>`).join('')}</div>${haccpFields()}<label class="field">내용 및 조치사항<textarea id="hDetail"></textarea></label><button id="saveHaccp" class="save" style="--house:var(--g)">${haccpType} 저장</button></div><div class="card records"><h2>${haccpType} 전체기록 · 최근순</h2>${records.map(x=>`<div class="record"><strong>${x.date.slice(5)}</strong><div><b>${x.target||x.type} · ${x.house?x.house+'동':'농장전체'}</b><span>${x.product?x.product+' · ':''}${x.detail}</span></div></div>`).join('')||'<p class="empty">기록이 없습니다.</p>'}</div>`);document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{haccpType=b.dataset.type;haccpView()});document.querySelectorAll('[data-hhouse]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.hhouse);haccpView()});$('#saveHaccp').onclick=saveHaccp;$('#printQuarter').onclick=()=>printQuarter(Number($('#reportYear').value),Number($('#reportQ').value))}
function haccpFields(){if(haccpType==='오늘점검')return `<div class="number-grid"><label>온도<input id="hTemp" type="number" step=".1"></label><label>습도<input id="hHumidity" type="number"></label></div><div class="checks">${['사료 정상','급수 정상','환기 정상','깔짚·바닥 정상','계군 건강 정상','폐사체 처리 완료'].map(x=>`<button type="button" data-check="${x}">${x}</button>`).join('')}</div>`;if(haccpType==='소독·방역')return `<label class="field">작업 구분<select id="hTarget"><option>계사 외부소독</option><option>계사 내부소독</option><option>방충·방서</option></select></label><label class="field">사용 약품<input id="hProduct"></label>`;if(haccpType==='약품관리')return `<label class="field">약품명<input id="hProduct"></label><div class="number-grid"><label>수량<input id="hAmount" type="number"></label><label>단위<select id="hUnit"><option>mL</option><option>L</option><option>g</option><option>kg</option><option>병</option></select></label></div>`;return `<label class="field">교육명<input id="hProduct"></label><label class="field">참석자<input id="hTarget"></label>`}
function saveHaccp(){const rowLocal={id:uid(),date:$('#hDate').value,type:haccpType,house:selected,target:$('#hTarget')?.value||'',product:$('#hProduct')?.value||'',amount:Number($('#hAmount')?.value||0),unit:$('#hUnit')?.value||'',temp:$('#hTemp')?.value||'',humidity:$('#hHumidity')?.value||'',detail:$('#hDetail').value,createdAt:new Date().toISOString()};db.haccp.push(rowLocal);let sheet='HACCP일일점검',row={id:rowLocal.id,날짜:rowLocal.date,대상동:selected,온도:rowLocal.temp,습도:rowLocal.humidity,점검항목:'',결과:'정상',내용및조치:rowLocal.detail,입력시간:rowLocal.createdAt,기기ID:deviceId(),deleted:false};if(haccpType==='소독·방역'){sheet='소독방역기록';row={id:rowLocal.id,날짜:rowLocal.date,대상동:selected,작업구분:rowLocal.target,사용약품:rowLocal.product,결과:'정상',내용및조치:rowLocal.detail,입력시간:rowLocal.createdAt,기기ID:deviceId(),deleted:false}}if(haccpType==='약품관리'){sheet='약품입고';row={id:rowLocal.id,날짜:rowLocal.date,약품명:rowLocal.product,입고량:rowLocal.amount,단위:rowLocal.unit,잔량:rowLocal.amount,입력시간:rowLocal.createdAt,기기ID:deviceId(),deleted:false}}if(haccpType==='교육'){sheet='교육기록';const d=new Date(rowLocal.date);row={id:rowLocal.id,날짜:rowLocal.date,연도:d.getFullYear(),분기:Math.floor(d.getMonth()/3)+1,교육명:rowLocal.product,참석자:rowLocal.target,교육내용:rowLocal.detail,입력시간:rowLocal.createdAt,기기ID:deviceId(),deleted:false}}queue(sheet,row);toast(`${haccpType} 저장 완료`);haccpView()}
function printQuarter(year,q){const rows=db.haccp.filter(x=>{const d=new Date(x.date);return d.getFullYear()===year&&Math.floor(d.getMonth()/3)+1===q}).sort((a,b)=>a.date.localeCompare(b.date));const old=$('#view').innerHTML;page(`${year}년 ${q}분기 HACCP 보고서`,'청운농장 상시 관리기록',`<div class="card print-report"><p><b>기간:</b> ${year}-${String((q-1)*3+1).padStart(2,'0')}-01 ~ ${year}-${String(q*3).padStart(2,'0')}-${new Date(year,q*3,0).getDate()}</p><div class="table-wrap"><div class="table"><div class="tr head"><b>일자</b><b>구분</b><b>대상</b><b>약품·교육</b><b>내용</b><b>결과</b></div>${rows.map(x=>`<div class="tr"><span>${x.date}</span><span>${x.type}</span><span>${x.house?x.house+'동':'전체'}</span><span>${x.product||'-'}</span><span>${x.detail||'-'}</span><span>정상</span></div>`).join('')}</div></div><p style="margin-top:35px">작성자: __________________　 농장책임자: __________________　 확인일: __________________</p></div><button class="save no-print" style="--house:var(--g)" onclick="window.print()">인쇄·PDF 저장</button><button class="save no-print" style="--house:#657169;margin-top:8px" id="backHaccp">돌아가기</button>`);$('#backHaccp').onclick=()=>{$('#view').innerHTML=old;haccpView()}}
function deviceId(){let id=localStorage.getItem('cheongun-device');if(!id){id=uid();localStorage.setItem('cheongun-device',id)}return id}
window.addEventListener('online',sync);window.addEventListener('offline',sync);if(accessToken){$('#login').style.display='none';$('#login').hidden=true;$('#app').hidden=false;$('#app').style.display='block';render();sync()}else{$('#login').style.display='grid';$('#login').hidden=false;$('#app').hidden=true}
