const API='https://script.google.com/macros/s/AKfycbyUOaqnkX1VSrBJ3Ee7IcPMcbRsmrikeotDfqn7IXsyvsCfcXS6CRDeF3o86Wzu366ojg/exec';
const COLORS=['#dc2626','#ea580c','#d99a00','#16803a','#2563eb'],SOFT=['#fef2f2','#fff7ed','#fffbeb','#f0fdf4','#eff6ff'];
const $=s=>document.querySelector(s), uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random(), today=()=>new Date().toISOString().slice(0,10), fmt=n=>Number(n||0).toLocaleString('ko-KR');
let password=localStorage.getItem('cheongun-password')||'', tab='home', selected=1, haccpType='오늘점검';
let db=JSON.parse(localStorage.getItem('cheongun-local')||'null')||{placementDate:today(),bonus:3,houses:[20000,20000,20000,20000,20000],entries:[],shipments:[],haccp:[],medicine:[],queue:[]};
const saveLocal=()=>localStorage.setItem('cheongun-local',JSON.stringify(db));
const age=()=>Math.max(1,Math.min(40,Math.floor((new Date(today())-new Date(db.placementDate))/86400000)+1));
const toast=m=>{const x=$('#toast');x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2500)};
async function api(body){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...body,password})});return r.json()}
function setSync(cls,text){const x=$('#syncState');x.className='sync '+cls;x.textContent='● '+text}
async function sync(){if(!password||!navigator.onLine){setSync('off','오프라인 저장');return}try{setSync('','동기화 중');if(db.queue.length){const q=[...db.queue],r=await api({action:'push',operations:q});if(!r.ok)throw Error(r.error);db.queue=[];saveLocal()}setSync('ok','시트 동기화 완료')}catch(e){setSync('off','전송 대기 '+db.queue.length+'건')}}
function queue(sheet,row){db.queue.push({sheet,row});saveLocal();sync()}
async function login(e){e.preventDefault();const p=$('#password').value;$('#loginError').textContent='확인 중...';try{password=p;const r=await api({action:'login'});if(!r.ok)throw Error(r.error);localStorage.setItem('cheongun-password',p);$('#login').hidden=true;$('#app').hidden=false;render();sync()}catch(err){password='';$('#loginError').textContent='비밀번호가 맞지 않거나 연결할 수 없습니다.'}}
$('#loginForm').addEventListener('submit',login);$('#nav').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;tab=b.dataset.tab;document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===b));render()});
function render(){ $('#ageLabel').textContent=`입추 ${db.placementDate} · ${age()}일령`;({home:homeView,journal:journalView,graph:graphView,ship:shipView,settings:settingsView,haccp:haccpView}[tab]||homeView)() }
function page(title,sub,body){$('#view').innerHTML=`<div class="page"><div class="title"><div><h1>${title}</h1><p>${sub}</p></div></div>${body}</div>`}
function todayByHouse(h){return db.entries.filter(x=>x.date===today()&&x.house===h).reduce((a,x)=>({death:a.death+x.death,cull:a.cull+x.cull}),{death:0,cull:0})}
function cumulative(h,key){return db.entries.filter(x=>x.house===h).reduce((s,x)=>s+Number(x[key]||0),0)}
function homeView(){page('당일 기록',`${today()} · ${age()}일령`,`
 <div class="card"><div class="houses">${[1,2,3,4,5].map(h=>`<button style="--c:${COLORS[h-1]}" data-house="${h}" class="${selected===h?'active':''}">${h}동</button>`).join('')}</div><div class="number-grid"><label>폐사수<input id="death" type="number" inputmode="numeric" min="0" value="0"></label><label>도태수<input id="cull" type="number" inputmode="numeric" min="0" value="0"></label></div><label class="field">특이사항<textarea id="note" placeholder="특이사항이 있으면 입력하세요"></textarea></label><button id="saveEntry" class="save" style="--house:${COLORS[selected-1]}">${selected}동 기록 저장</button></div>
 <div class="card"><h2>오늘 동별 합계</h2><div class="totals">${[1,2,3,4,5].map(h=>{const t=todayByHouse(h);return `<div class="total-row" style="--c:${COLORS[h-1]};--soft:${SOFT[h-1]}"><strong>${h}동</strong><div><span>합계</span><b>${t.death+t.cull}</b></div><div><span>폐사</span><b>${t.death}</b></div><div><span>도태</span><b>${t.cull}</b></div></div>`}).join('')}</div></div>
 <div class="card records"><h2>오늘 입력기록</h2>${db.entries.filter(x=>x.date===today()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(x=>`<div class="record"><strong>${x.house}동</strong><div><b>폐사 ${x.death} · 도태 ${x.cull} · 합계 ${x.death+x.cull}</b><span>${x.note||'특이사항 없음'}</span><small>${new Date(x.createdAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</small></div><button data-del-entry="${x.id}">삭제</button></div>`).join('')||'<p class="empty">오늘 입력한 기록이 없습니다.</p>'}</div>`);
 document.querySelectorAll('[data-house]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.house);homeView()});$('#saveEntry').onclick=()=>{const death=Number($('#death').value),cull=Number($('#cull').value),note=$('#note').value.trim();if(!death&&!cull&&!note)return toast('입력할 내용을 확인하세요');const row={id:uid(),회차ID:db.placementDate,날짜:today(),일령:age(),동:selected,폐사:death,도태:cull,특이사항:note,입력시간:new Date().toISOString(),기기ID:deviceId(),updatedAt:new Date().toISOString(),deleted:false};db.entries.push({id:row.id,date:row.날짜,age:row.일령,house:selected,death,cull,note,createdAt:row.입력시간});queue('폐사도태기록',row);toast(`${selected}동 기록 저장 완료`);homeView()};document.querySelectorAll('[data-del-entry]').forEach(b=>b.onclick=()=>{const x=db.entries.find(y=>y.id===b.dataset.delEntry);db.entries=db.entries.filter(y=>y.id!==x.id);queue('폐사도태기록',{id:x.id,회차ID:db.placementDate,날짜:x.date,일령:x.age,동:x.house,폐사:x.death,도태:x.cull,특이사항:x.note,입력시간:x.createdAt,기기ID:deviceId(),deleted:true});homeView()})}
function journalView(){const rows=[];for(let d=age();d>=1;d--){const es=db.entries.filter(x=>x.age===d),de=es.reduce((s,x)=>s+x.death,0),cu=es.reduce((s,x)=>s+x.cull,0),sh=db.shipments.filter(x=>x.age===d).reduce((s,x)=>s+x.count,0),dead=db.entries.filter(x=>x.age<=d).reduce((s,x)=>s+x.death+x.cull,0),shipped=db.shipments.filter(x=>x.age<=d).reduce((s,x)=>s+x.count,0);rows.push(`<div class="tr"><b>${d}일령</b><span>${de}</span><span>${cu}</span><span>${de+cu}</span><span>${sh||'-'}</span><strong>${fmt(db.houses.reduce((a,b)=>a+b,0)-dead-shipped)}</strong></div>`)}page('일령별 사육일지','최근 일령부터 표시',`<div class="card"><div class="table-wrap"><div class="table"><div class="tr head"><b>일령</b><b>폐사</b><b>도태</b><b>폐·도태</b><b>부분출하</b><b>현재사육수</b></div>${rows.join('')}</div></div></div>`)}
function graphView(){const vals=[1,2,3,4,5].map(h=>cumulative(h,'death')+cumulative(h,'cull')),max=Math.max(1,...vals);page('그래프 보기','동별 누적 폐·도태',`<div class="card bars">${vals.map((v,i)=>`<div class="bar" style="--c:${COLORS[i]};--w:${Math.max(3,v/max*100)}%"><b>${i+1}동</b><i></i><strong>${v}수</strong></div>`).join('')}</div>`)}
function shipView(){page('부분출하','출하 즉시 현재 사육수에 반영',`<div class="card"><div class="houses">${[1,2,3,4,5].map(h=>`<button style="--c:${COLORS[h-1]}" data-house="${h}" class="${selected===h?'active':''}">${h}동</button>`).join('')}</div><div class="number-grid"><label>부분출하수<input id="shipCount" type="number" inputmode="numeric" min="0"></label><label>출하일<input id="shipDate" type="date" value="${today()}"></label></div><label class="field">특이사항<textarea id="shipNote"></textarea></label><button id="saveShip" class="save" style="--house:${COLORS[selected-1]}">${selected}동 부분출하 저장</button></div><div class="card records"><h2>부분출하 기록</h2>${db.shipments.slice().reverse().map(x=>`<div class="record"><strong>${x.house}동</strong><div><b>${fmt(x.count)}수</b><span>${x.date} · ${x.note||'특이사항 없음'}</span></div></div>`).join('')||'<p class="empty">기록이 없습니다.</p>'}</div>`);document.querySelectorAll('[data-house]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.house);shipView()});$('#saveShip').onclick=()=>{const count=Number($('#shipCount').value);if(!count)return;const row={id:uid(),회차ID:db.placementDate,날짜:$('#shipDate').value,일령:age(),동:selected,출하수:count,특이사항:$('#shipNote').value,입력시간:new Date().toISOString(),기기ID:deviceId(),deleted:false};db.shipments.push({id:row.id,date:row.날짜,age:row.일령,house:selected,count,note:row.특이사항});queue('부분출하기록',row);toast('부분출하 저장 완료');shipView()}}
function settingsView(){page('사육 회차 설정','한 파스 종료 시 새 회차 시작',`<div class="card"><label class="field">입추일<input id="placement" type="date" value="${db.placementDate}"></label><label class="field">덤 비율(참고)<input id="bonus" type="number" step=".1" value="${db.bonus}"></label>${db.houses.map((n,i)=>`<div class="setting-row"><b>${i+1}동 공식 입추수</b><input data-official="${i}" type="number" value="${n}"></div>`).join('')}<button id="saveSettings" class="save" style="--house:var(--g);margin-top:14px">설정 저장</button></div><div class="card"><b>새 사육 회차</b><p>전량 출하 후 시작하면 사육기록만 새로 시작하며 HACCP 자료는 계속 보존됩니다.</p><button id="newFlock" class="save" style="--house:#8b2f2f">새 파스 시작</button></div>`);$('#saveSettings').onclick=()=>{db.placementDate=$('#placement').value;db.bonus=Number($('#bonus').value);document.querySelectorAll('[data-official]').forEach(x=>db.houses[Number(x.dataset.official)]=Number(x.value));db.houses.forEach((n,i)=>queue('계사정보',{id:`${db.placementDate}-${i+1}`,회차ID:db.placementDate,동:i+1,공식입추수:n,createdAt:new Date().toISOString()}));saveLocal();toast('설정 저장 완료');render()};$('#newFlock').onclick=()=>{if(!confirm('사육기록을 새 파스로 시작할까요? HACCP 기록은 유지됩니다.'))return;db.entries=[];db.shipments=[];db.placementDate=today();saveLocal();render()}}
function haccpView(){const types=['오늘점검','소독·방역','약품관리','교육'],records=db.haccp.filter(x=>x.type===haccpType).sort((a,b)=>b.date.localeCompare(a.date));page('HACCP 상시관리','사육 파스와 별도로 계속 보관',`<div class="card report-tools"><select id="reportYear"><option>${new Date().getFullYear()}</option><option>${new Date().getFullYear()-1}</option></select><select id="reportQ">${[1,2,3,4].map(q=>`<option value="${q}" ${Math.floor(new Date().getMonth()/3)+1===q?'selected':''}>${q}분기</option>`).join('')}</select><button id="printQuarter">분기 PDF</button></div><div class="haccp-types">${types.map(x=>`<button data-type="${x}" class="${haccpType===x?'active':''}">${x}</button>`).join('')}</div><div class="card" style="margin-top:10px"><label class="field">기록일<input id="hDate" type="date" value="${today()}"></label><div class="houses" style="margin:10px 0">${[0,1,2,3,4,5].map(h=>`<button style="--c:${h?COLORS[h-1]:'#176b3a'}" data-hhouse="${h}" class="${selected===h?'active':''}">${h?`${h}동`:'전체'}</button>`).join('')}</div>${haccpFields()}<label class="field">내용 및 조치사항<textarea id="hDetail"></textarea></label><button id="saveHaccp" class="save" style="--house:var(--g)">${haccpType} 저장</button></div><div class="card records"><h2>${haccpType} 전체기록 · 최근순</h2>${records.map(x=>`<div class="record"><strong>${x.date.slice(5)}</strong><div><b>${x.target||x.type} · ${x.house?x.house+'동':'농장전체'}</b><span>${x.product?x.product+' · ':''}${x.detail}</span></div></div>`).join('')||'<p class="empty">기록이 없습니다.</p>'}</div>`);document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{haccpType=b.dataset.type;haccpView()});document.querySelectorAll('[data-hhouse]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.hhouse);haccpView()});$('#saveHaccp').onclick=saveHaccp;$('#printQuarter').onclick=()=>printQuarter(Number($('#reportYear').value),Number($('#reportQ').value))}
function haccpFields(){if(haccpType==='오늘점검')return `<div class="number-grid"><label>온도<input id="hTemp" type="number" step=".1"></label><label>습도<input id="hHumidity" type="number"></label></div><div class="checks">${['사료 정상','급수 정상','환기 정상','깔짚·바닥 정상','계군 건강 정상','폐사체 처리 완료'].map(x=>`<button type="button" data-check="${x}">${x}</button>`).join('')}</div>`;if(haccpType==='소독·방역')return `<label class="field">작업 구분<select id="hTarget"><option>계사 외부소독</option><option>계사 내부소독</option><option>방충·방서</option></select></label><label class="field">사용 약품<input id="hProduct"></label>`;if(haccpType==='약품관리')return `<label class="field">약품명<input id="hProduct"></label><div class="number-grid"><label>수량<input id="hAmount" type="number"></label><label>단위<select id="hUnit"><option>mL</option><option>L</option><option>g</option><option>kg</option><option>병</option></select></label></div>`;return `<label class="field">교육명<input id="hProduct"></label><label class="field">참석자<input id="hTarget"></label>`}
function saveHaccp(){const rowLocal={id:uid(),date:$('#hDate').value,type:haccpType,house:selected,target:$('#hTarget')?.value||'',product:$('#hProduct')?.value||'',amount:Number($('#hAmount')?.value||0),unit:$('#hUnit')?.value||'',temp:$('#hTemp')?.value||'',humidity:$('#hHumidity')?.value||'',detail:$('#hDetail').value,createdAt:new Date().toISOString()};db.haccp.push(rowLocal);let sheet='HACCP일일점검',row={id:rowLocal.id,날짜:rowLocal.date,대상동:selected,온도:rowLocal.temp,습도:rowLocal.humidity,점검항목:'',결과:'정상',내용및조치:rowLocal.detail,입력시간:rowLocal.createdAt,기기ID:deviceId(),deleted:false};if(haccpType==='소독·방역'){sheet='소독방역기록';row={id:rowLocal.id,날짜:rowLocal.date,대상동:selected,작업구분:rowLocal.target,사용약품:rowLocal.product,결과:'정상',내용및조치:rowLocal.detail,입력시간:rowLocal.createdAt,기기ID:deviceId(),deleted:false}}if(haccpType==='약품관리'){sheet='약품입고';row={id:rowLocal.id,날짜:rowLocal.date,약품명:rowLocal.product,입고량:rowLocal.amount,단위:rowLocal.unit,잔량:rowLocal.amount,입력시간:rowLocal.createdAt,기기ID:deviceId(),deleted:false}}if(haccpType==='교육'){sheet='교육기록';const d=new Date(rowLocal.date);row={id:rowLocal.id,날짜:rowLocal.date,연도:d.getFullYear(),분기:Math.floor(d.getMonth()/3)+1,교육명:rowLocal.product,참석자:rowLocal.target,교육내용:rowLocal.detail,입력시간:rowLocal.createdAt,기기ID:deviceId(),deleted:false}}queue(sheet,row);toast(`${haccpType} 저장 완료`);haccpView()}
function printQuarter(year,q){const rows=db.haccp.filter(x=>{const d=new Date(x.date);return d.getFullYear()===year&&Math.floor(d.getMonth()/3)+1===q}).sort((a,b)=>a.date.localeCompare(b.date));const old=$('#view').innerHTML;page(`${year}년 ${q}분기 HACCP 보고서`,'청운농장 상시 관리기록',`<div class="card print-report"><p><b>기간:</b> ${year}-${String((q-1)*3+1).padStart(2,'0')}-01 ~ ${year}-${String(q*3).padStart(2,'0')}-${new Date(year,q*3,0).getDate()}</p><div class="table-wrap"><div class="table"><div class="tr head"><b>일자</b><b>구분</b><b>대상</b><b>약품·교육</b><b>내용</b><b>결과</b></div>${rows.map(x=>`<div class="tr"><span>${x.date}</span><span>${x.type}</span><span>${x.house?x.house+'동':'전체'}</span><span>${x.product||'-'}</span><span>${x.detail||'-'}</span><span>정상</span></div>`).join('')}</div></div><p style="margin-top:35px">작성자: __________________　 농장책임자: __________________　 확인일: __________________</p></div><button class="save no-print" style="--house:var(--g)" onclick="window.print()">인쇄·PDF 저장</button><button class="save no-print" style="--house:#657169;margin-top:8px" id="backHaccp">돌아가기</button>`);$('#backHaccp').onclick=()=>{$('#view').innerHTML=old;haccpView()}}
function deviceId(){let id=localStorage.getItem('cheongun-device');if(!id){id=uid();localStorage.setItem('cheongun-device',id)}return id}
window.addEventListener('online',sync);window.addEventListener('offline',sync);if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');if(password){$('#login').hidden=true;$('#app').hidden=false;render();sync()}
